# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./test_function.h \
    ./Test.h
SOURCES += ./main.cpp \
    ./Test.cpp \
    ./test_function.c
FORMS += ./Test.ui
RESOURCES += Test.qrc
